CREATE TABLE LOGIN(
	ID INTEGER PRIMARY KEY,
	STR_LOGIN VARCHAR(100) NOT NULL UNIQUE,
	STR_SENHA TEXT NOT NULL,
	CREATED_AT DATE DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE USUARIOS (
	ID INTEGER PRIMARY KEY,
	STR_NOME VARCHAR(100) NOT NULL,
	STR_CELULAR VARCHAR(50),
	STR_EMAIL VARCHAR(100),
	STR_GENERO CHAR(1) NOT NULL,
	INT_CGC INT,
	STR_TIPO INT NOT NULL
		CHECK(
			STR_TIPO = 'F' OR	-- QUANDO FOR PESSOA FISICA
			STR_TIPO = 'J'		-- QUANDO FOR PESSOA JURIDICA
		) DEFAULT 'F',
	DAT_NASC DATE,
	ID_ENDERECO INT REFERENCES ENDERECOS(ID) NULL,
	CREATED_AT DATE DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATE DEFAULT CURRENT_TIMESTAMP
);

--DATE DATA E HORA
--CURRENT_TIMESTAMPEGA DATA/HORA DO SISTEMA POR PADRÃO
--CGC - CNPJ OU CPF

CREATE TABLE ONGS (
	ID INT PRIMARY KEY,
	STR_DIR_IMG TEXT,
	STR_NOME VARCHAR(100) NOT NULL,
	STR_DESC TEXT,
	STR_TELEFONE VARCHAR(50) NOT NULL,
	STR_EMAIL VARCHAR(100) NOT NULL,
	INT_CNPJ INT NOT NULL,
	ID_ENDERECO INT REFERENCES ENDERECOS(ID) NULL,
	CREATED_AT DATE DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ENDERECOS (
	ID INT PRIMARY KEY,
	STR_CEP CHAR(9),
	STR_LOGRADOURO VARCHAR(100),
	STR_BAIRRO VARCHAR(100),
	STR_NUMERO VARCHAR(20),
	STR_CIDADE VARCHAR(50),
	STR_ESTADO CHAR(2),
	STR_ORIGEM VARCHAR(20),
	CREATED_AT DATE DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATE DEFAULT CURRENT_TIMESTAMP
);

--TABELA PARA QUEM FOR UTILIZAR OS RECURSOS DA ONG E NÃO POSSUEM TODOS OS DADOS, COMO OS MORADORES DE RUA.
--COMO MORADORES DE RUAS N POSSUEM CEL OU EMAIL NAO É OBRIGATÓRIO
-- CREATE TABLE BENEFICIARIOS(
-- 	ID INT PRIMARY KEY,
-- 	STR_NOME VARCHAR(100) NOT NULL,
-- 	STR_CELULAR VARCHAR(50),
-- 	STR_EMAIL VARCHAR(100),
-- 	STR_GENERO CHAR(1) NOT NULL,
-- 	INT_CGC INT NOT NULL,
-- 	DAT_NASC DATE NOT NULL,
-- 	CREATED_AT DATE DEFAULT CURRENT_TIMESTAMP,
-- 	UPDATED_AT DATE DEFAULT CURRENT_TIMESTAMP
-- );

--TABELA BENEFICENCIAS DECLARA QUAIS PESSOAS ESTAO SENDO BENEFICIADAS POR CADA ONG
CREATE TABLE BENEFICENCIAS(
	ID INT PRIMARY KEY,
	ID_USUARIO INT REFERENCES USUARIOS(ID),
	ID_ONG INT REFERENCES ONGS(ID),
	CREATED_AT DATE DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PROJETOS(
	ID INT PRIMARY KEY,
	STR_DESC TEXT,
	ID_USUARIO INT REFERENCES USUARIOS(ID),
	DAT_FIM DATE,
	CREATED_AT DATE DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE POSTAGENS(
	ID INT PRIMARY KEY,
	STR_TEXTO TEXT,
	ID_USUARIO INT REFERENCES USUARIOS(ID),
	CREATED_AT DATE DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATE DEFAULT CURRENT_TIMESTAMP
);

--TABELA ONDE IRÁ TODOS OS ARQUIVOS DE USO DO SISTEMA
CREATE TABLE ARQUIVOS(
	ID INT PRIMARY KEY,
	CONTEUDO BLOB NOT NULL,
	STR_DESCRICAO TEXT,
	CREATED_AT DATE DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATE DEFAULT CURRENT_TIMESTAMP
);

-- TABELA PARA ARMAZENAR OS RELACIONAMENTOS DE USO DE ARQUIVOS
CREATE TABLE ARQUIVOS_USOS(
	ID INT PRIMARY KEY,
	ID_ARQUIVO INT REFERENCES ARQUIVOS (ID),
	ID_USO INT,
	STR_TIPO_USO
		VARCHAR(1)
		NOT NULL
		CHECK(
			STR_TIPO_USO = 'U' OR	-- QUANDO USADO EM USUARIO
			STR_TIPO_USO = 'C' OR	-- QUANDO USADO EM COMENTARIO
			STR_TIPO_USO = 'P' OR	-- QUANDO USADO EM POSTAGENS
			STR_TIPO_USO = 'J' OR	-- QUANDO USADO EM PROJETOS
			STR_TIPO_USO = 'O'		-- QUANDO USADO EM ONGS
		) DEFAULT 'C',
	CREATED_AT DATE DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATE DEFAULT CURRENT_TIMESTAMP
);

--TABELA PARA COMENTARIOS DE UMA POSTAGEM
--ID_POSTAGEM PEGA O ID DA POSTAGEM
--ID-USUARIO QUEM FEZ O COMENTARIO
CREATE TABLE COMENTARIOS(
	ID INT PRIMARY KEY,
	STR_COMENT TEXT,
	ID_USUARIO INT REFERENCES USUARIOS(ID),
	ID_POSTAGEM INT REFERENCES POSTAGENS(ID),
	CREATED_AT DATE DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATE DEFAULT CURRENT_TIMESTAMP
);

--TABELA DE CURTIDAS
CREATE TABLE CURTIDAS(
	ID INT PRIMARY KEY,
	ID_USUARIO INT REFERENCES USUARIOS(ID),
	ID_ORIGEM INT NOT NULL,
	STR_TIPO_CURTIDA
		VARCHAR(1)
		NOT NULL
		CHECK(
			STR_TIPO_CURTIDA = 'C' OR	-- QUANDO USADO EM COMENTARIO
			STR_TIPO_CURTIDA = 'P' OR	-- QUANDO USADO EM POSTAGENS
			STR_TIPO_CURTIDA = 'J' OR	-- QUANDO USADO EM PROJETOS
			STR_TIPO_CURTIDA = 'O'		-- QUANDO USADO EM ONGS
		) DEFAULT 'C',
	CREATED_AT DATE DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATE DEFAULT CURRENT_TIMESTAMP
);
